data = struct( ...
    'W_S', W_S_des_memo(1:indice_contatore), ...
    'S', S_ref_memo(1:indice_contatore), ...
    'S_wet', S_wet_memo(1:indice_contatore), ...
    'S_vert', S_vert_memo(1:indice_contatore), ...
    'S_orizz', S_orizz_memo(1:indice_contatore), ...
    'b', b_ref_memo(1:indice_contatore), ...
    'lambda', lambda_des_memo(1:indice_contatore), ...
    'c_root', croot_memo(1:indice_contatore), ...
    'c_tip', ctip_memo(1:indice_contatore), ...
    'MAC', MAC_memo(1:indice_contatore), ...
    'AR', AR_des_memo(1:indice_contatore), ...
    't_c', t_c_des_memo(1:indice_contatore), ...
    'sweep25', sweep25_des_memo(1:indice_contatore), ...
    'V_fuel', W_fuel_memo(1:indice_contatore) / 0.8, ...
    ...
    'M', M_des_memo(1:indice_contatore), ...
    'W_fuel', W_fuel_memo(1:indice_contatore), ...
    'W_block_fuel', W_block_fuel_memo(1:indice_contatore), ...
    'E_crociera', E_curr_memo(1:indice_contatore), ...
    'CD', CD_curr_memo(1:indice_contatore), ...
    'Cd0', Cd0_memo(1:indice_contatore), ...
    'Cdi', Cdi_memo(1:indice_contatore), ...
    'Cdw', Cdw_memo(1:indice_contatore), ...
    'CL_crociera', CL_des_memo(1:indice_contatore), ...
    'CL_max', CL_max_memo(1:indice_contatore), ...
    'T', T_curr_memo(1:indice_contatore), ...
    'T_W', thrust_ratio_memo(1:indice_contatore), ...
    ...
    'WTO', WTO_memo(1:indice_contatore), ...
    'OEW', OEW_memo(1:indice_contatore), ...
    'W_wing', W_wing_memo(1:indice_contatore), ...
    'W_tail', W_tail_memo(1:indice_contatore), ...
    'W_LG', W_LG_memo(1:indice_contatore), ...
    'W_propuls', W_propuls_memo(1:indice_contatore), ...
    'W_fuelsys', W_fuelsys_memo(1:indice_contatore), ...
    'W_hydr', W_hydr_memo(1:indice_contatore), ...
    ...
    'ADP', ADP_memo(1:indice_contatore), ...
    'flight_cost', flight_cost_memo(1:indice_contatore), ...
    'maintenance_cost', maintenance_cost_memo(1:indice_contatore), ...
    'DOC', DOC_memo(1:indice_contatore), ...
    'PREE', PREE_memo(1:indice_contatore) ...
    );
timestamp = datestr(datetime('now'), 'yyyy-mm-dd_HH-MM-SS');
filename = ['dati_convergenza_' timestamp '.csv'];
writetable(struct2table(data), filename);